on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Deploy to heroku app

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.1
    - name: npm install, build
      run: |
        npm install
        npm run build
    - name: Deploy Docker Image to Heroku App
      # You may pin to the exact commit or the version.
      # uses: jctaveras/heroku-deploy@66bad8e81927dbf4a39ef8364a4c2f3043233ce0
      uses: jctaveras/heroku-deploy@v2.1.3
      with:
        # Email Linked to your Heroku Account
        email: andoni2222@gmail.com
        # Heroku Dyno Formation
        #formation: # optional, default is web
        # Your Heroku API Key
        api_key: ${{ secrets.HEROKU_API_KEY }}
        # Your Heroku App Name
        app_name: test-andoni2
        # Dokerfile path
        #dockerfile_path: 
        # Optional build parameters
        #options: # optional
